using System;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Wino.SourceGenerators.Preferences;

/// <summary>
/// Generates the strongly typed preference accessor table used by PreferencesService.
/// This removes PropertyInfo/GetValue/SetValue from settings import and export so the
/// feature remains functional when reflection metadata is trimmed by Native AOT.
/// </summary>
[Generator]
public sealed class PreferencesPropertyGenerator : IIncrementalGenerator
{
    private const string InterfaceMetadataName = "Wino.Core.Domain.Interfaces.IPreferencesService";
    private static readonly string[] ServiceMetadataNames =
    [
        "Wino.Mail.WinUI.Services.PreferencesService",
        "Wino.Platform.Windows.Services.PreferencesService"
    ];

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var model = context.CompilationProvider.Select(static (compilation, _) =>
        {
            var preferenceInterface = compilation.GetTypeByMetadataName(InterfaceMetadataName);
            var preferenceService = ServiceMetadataNames\n                .Select(compilation.GetTypeByMetadataName)\n                .FirstOrDefault(static symbol => symbol != null);

            if (preferenceInterface == null || preferenceService == null)
            {
                return (Namespace: string.Empty, Properties: ImmutableArray<IPropertySymbol>.Empty);
            }

            var properties = preferenceInterface
                .GetMembers()
                .OfType<IPropertySymbol>()
                .Where(static property =>
                    !property.IsIndexer &&
                    property.GetMethod != null &&
                    property.SetMethod != null &&
                    property.Name != "DiagnosticId")
                .OrderBy(static property => property.Name, StringComparer.Ordinal)
                .ToImmutableArray();

            return (
                Namespace: preferenceService.ContainingNamespace.ToDisplayString(),
                Properties: properties);
        });

        context.RegisterSourceOutput(model, static (sourceContext, properties) =>
        {
            if (properties.Properties.IsDefaultOrEmpty || string.IsNullOrEmpty(properties.Namespace))
            {
                return;
            }

            var source = new StringBuilder();
            source.AppendLine("// <auto-generated />");
            source.AppendLine("#nullable enable");
            source.Append("namespace ").Append(properties.Namespace).AppendLine(";");
            source.AppendLine();
            source.AppendLine("public partial class PreferencesService");
            source.AppendLine("{");
            source.AppendLine("    private static partial PreferenceAccessor[] GetGeneratedSyncablePreferenceProperties() =>");
            source.AppendLine("        new PreferenceAccessor[]");
            source.AppendLine("        {");

            foreach (var property in properties.Properties)
            {
                var typeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
                source.Append("            new(\"")
                    .Append(property.Name)
                    .Append("\", typeof(")
                    .Append(typeName)
                    .Append("), static service => service.")
                    .Append(property.Name)
                    .Append(", static (service, value) => service.")
                    .Append(property.Name)
                    .Append(" = (")
                    .Append(typeName)
                    .AppendLine(")value!),");
            }

            source.AppendLine("        };");
            source.AppendLine("}");

            sourceContext.AddSource("PreferencesService.Accessors.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
        });
    }
}
